// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SynthParams } from "./SynthParams";
import type { TrackSnapshot } from "./TrackSnapshot";

export type AudioStateSnapshot = { is_playing: boolean, playhead_position: number, tempo: number, is_looping: boolean, loop_start: number, loop_end: number, synth: SynthParams, tracks: Array<TrackSnapshot>, master_volume?: number };
