// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeterData = { master_peak: [number, number], track_peaks: { [key in number]?: [number, number] }, };
